[workspace]
members = [
    "satellite_core/",
    "context_builder/",
]

[package]
name = "satellite"
version = "0.1.0"
authors = ["Matthias Seiffert <lythenas@hotmail.de>"]

[dependencies]
satellite_core = { path = "satellite_core/" }
