[package]
name = "context_builder"
version = "0.1.0"
authors = ["Matthias Seiffert <lythenas@hotmail.de>"]
description = "Context Builder for Rocket Templates."

[dependencies]
rocket = "0.3"
rocket_codegen = "0.3"
serde = "1.0"
serde_derive = "1.0"
regex = "0.2"
toml = "0.4"
maplit = "1.0"
