CREATE TABLE posts (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  title VARCHAR NOT NULL,
  slug VARCHAR NOT NULL,
  body TEXT NOT NULL,
  author VARCHAR NOT NULL,
  published_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)